# Site settings
title: Tucker DeWitt
company: Misfit Development, LLC
email: inbound@misfit.dev
url: https://github.com/tdewitt/tdewitt.github.io
description: "Misfit Development, LLC Portfolio"
keywords: "tucker dewitt, devops, security, compliance, soc2, iso27001, sre, reliability, advisory, startup, startups, saas, tech"
skills: "Reliability - DevOps - Security - Compliance"
meta_author: DeWitt, Tucker

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 91a3b0 #80B3FF
  primary-rgb: "128,128,128" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Misfit Development, LLC
  location: Location
  social: Social
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/tdew/

# Postal address (add as many lines as necessary)
address:
  - line: 11 Squamscott Rd
  - line: Stratham, NH 03885

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
